<?php

/**
 * BaseEmployeeAdjSalary
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $empNumber
 * @property integer $adjPayGradeId
 * @property string $adjPayPeriodId
 * @property integer $year
 * @property integer $term_id
 * @property integer $credits_taught
 * @property intger $reduced_credit
 * @property integer $total_credits
 * @property intger $hours
 * @property string $notes
 * @property Employee $employee
 * @property AdjPayGrade $payGrade
 * @property Payperiod $payperiod
 * 
 * @method integer           getId()             Returns the current record's "id" value
 * @method integer           getEmpNumber()      Returns the current record's "empNumber" value
 * @method integer           getAdjPayGradeId()  Returns the current record's "adjPayGradeId" value
 * @method string            getAdjPayPeriodId() Returns the current record's "adjPayPeriodId" value
 * @method integer           getYear()           Returns the current record's "year" value
 * @method integer           getTermId()         Returns the current record's "term_id" value
 * @method integer           getCreditsTaught()  Returns the current record's "credits_taught" value
 * @method intger            getReducedCredit()  Returns the current record's "reduced_credit" value
 * @method integer           getTotalCredits()   Returns the current record's "total_credits" value
 * @method intger            getHours()          Returns the current record's "hours" value
 * @method string            getNotes()          Returns the current record's "notes" value
 * @method Employee          getEmployee()       Returns the current record's "employee" value
 * @method AdjPayGrade       getPayGrade()       Returns the current record's "payGrade" value
 * @method Payperiod         getPayperiod()      Returns the current record's "payperiod" value
 * @method EmployeeAdjSalary setId()             Sets the current record's "id" value
 * @method EmployeeAdjSalary setEmpNumber()      Sets the current record's "empNumber" value
 * @method EmployeeAdjSalary setAdjPayGradeId()  Sets the current record's "adjPayGradeId" value
 * @method EmployeeAdjSalary setAdjPayPeriodId() Sets the current record's "adjPayPeriodId" value
 * @method EmployeeAdjSalary setYear()           Sets the current record's "year" value
 * @method EmployeeAdjSalary setTermId()         Sets the current record's "term_id" value
 * @method EmployeeAdjSalary setCreditsTaught()  Sets the current record's "credits_taught" value
 * @method EmployeeAdjSalary setReducedCredit()  Sets the current record's "reduced_credit" value
 * @method EmployeeAdjSalary setTotalCredits()   Sets the current record's "total_credits" value
 * @method EmployeeAdjSalary setHours()          Sets the current record's "hours" value
 * @method EmployeeAdjSalary setNotes()          Sets the current record's "notes" value
 * @method EmployeeAdjSalary setEmployee()       Sets the current record's "employee" value
 * @method EmployeeAdjSalary setPayGrade()       Sets the current record's "payGrade" value
 * @method EmployeeAdjSalary setPayperiod()      Sets the current record's "payperiod" value
 * 
 * @package    orangehrm
 * @subpackage model\pim\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmployeeAdjSalary extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_emp_adjsalary');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('emp_number as empNumber', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('adj_sal_grd_code as adjPayGradeId', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('adj_payperiod_code as adjPayPeriodId', 'string', 13, array(
             'type' => 'string',
             'length' => 13,
             ));
        $this->hasColumn('year', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('term_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('credits_taught', 'integer', 4, array(
             'type' => 'integer',
             'default' => '0',
             'length' => 4,
             ));
        $this->hasColumn('reduced_credit', 'intger', 4, array(
             'type' => 'intger',
             'default' => '0',
             'length' => 4,
             ));
        $this->hasColumn('total_credits', 'integer', 4, array(
             'type' => 'integer',
             'default' => '0',
             'length' => 4,
             ));
        $this->hasColumn('hours', 'intger', 4, array(
             'type' => 'intger',
             'default' => '0',
             'length' => 4,
             ));
        $this->hasColumn('comments as notes', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Employee as employee', array(
             'local' => 'empNumber',
             'foreign' => 'empNumber'));

        $this->hasOne('AdjPayGrade as payGrade', array(
             'local' => 'adjPayGradeId',
             'foreign' => 'id'));

        $this->hasOne('Payperiod as payperiod', array(
             'local' => 'adjPayPeriodId',
             'foreign' => 'payperiod_code'));
    }
}