<?php

/**
 * AdjPayGradeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdjPayGradeTable extends PluginAdjPayGradeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdjPayGradeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdjPayGrade');
    }
}