<?php

/**
 * PluginEthnicTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEthnicTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEthnicTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEthnic');
    }
}