<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/05/13 12:30:52

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=orangehrm',
  'username' => 'root',
  'password' => 'DJ02ar13',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
