<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/06/16 13:15:22
sfConfig::add(array(
  'mod_recruitmentapply_enabled' => true,
  'mod_recruitmentapply_view_class' => 'sfPHP',
));
