<?php

/**
 * BaseEthnic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Employee $Employee
 * 
 * @method integer  getId()       Returns the current record's "id" value
 * @method string   getName()     Returns the current record's "name" value
 * @method Employee getEmployee() Returns the current record's "Employee" value
 * @method Ethnic   setId()       Sets the current record's "id" value
 * @method Ethnic   setName()     Sets the current record's "name" value
 * @method Ethnic   setEmployee() Sets the current record's "Employee" value
 * 
 * @package    orangehrm
 * @subpackage model\admin\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEthnic extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_ethnic');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Employee', array(
             'local' => 'id',
             'foreign' => 'emp_ethnic'));
    }
}