<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        /*$this->dropTable('ohrm_beacon_notification');
        $this->dropTable('ohrm_data_group_screen');
        $this->dropTable('ohrm_datapoint');
        $this->dropTable('ohrm_datapoint_type');
        $this->dropTable('ohrm_module_default_page');
        $this->createTable('ohrm_adj_pay_grade', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '60',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('hs_hr_emp_adjsalary', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'emp_number' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
              'alias' => 'empNumber',
             ),
             'adj_sal_grd_code' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'alias' => 'adjPayGradeId',
             ),
             'year' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'term_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'credits_taught' => 
             array(
              'type' => 'integer',
              'default' => '0',
              'length' => '4',
             ),
             'reduced_credit' => 
             array(
              'type' => 'integer',
              'default' => '0',
              'length' => '4',
             ),
             'total_credits' => 
             array(
              'type' => 'integer',
              'default' => '0',
              'length' => '4',
             ),
             'hours' => 
             array(
              'type' => 'integer',
              'default' => '0',
              'length' => '4',
             ),
             'comments' => 
             array(
              'type' => 'string',
              'length' => '255',
              'alias' => 'notes',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));*/
    }

    public function down()
    {
        /*$this->createTable('ohrm_beacon_notification', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '100',
             ),
             'expiry_date' => 
             array(
              'type' => 'timestamp',
              'notnull' => '1',
              'length' => '25',
              'alias' => 'expiryDate',
             ),
             'definition' => 
             array(
              'type' => 'clob',
              'notnull' => '1',
              'length' => '',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => '',
             'charset' => '',
             ));
        $this->createTable('ohrm_data_group_screen', array(
             'id' => 
             array(
              'type' => 'integer',
              'autoincrement' => '1',
              'primary' => '1',
              'length' => '8',
             ),
             'data_group_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'screen_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'permission' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => '',
             'charset' => '',
             ));
        $this->createTable('ohrm_datapoint', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '100',
             ),
             'datapoint_type_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
              'alias' => 'datapointTypeId',
             ),
             'definition' => 
             array(
              'type' => 'clob',
              'notnull' => '1',
              'length' => '',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => '',
             'charset' => '',
             ));
        $this->createTable('ohrm_datapoint_type', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '100',
             ),
             'action_class' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
              'alias' => 'actionClass',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => '',
             'charset' => '',
             ));
        $this->createTable('ohrm_module_default_page', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
              'alias' => 'userId',
             ),
             'user_name' => 
             array(
              'type' => 'string',
              'length' => '255',
              'alias' => 'userName',
             ),
             'userrolename' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '',
             ),
             'user_role_predefined' => 
             array(
              'type' => 'boolean',
              'notnull' => '1',
              'length' => '25',
              'alias' => 'userRolePredefined',
             ),
             'login_time' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
              'alias' => 'loginTime',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => '',
             'charset' => '',
             ));*/
        $this->dropTable('ohrm_adj_pay_grade');
        $this->dropTable('hs_hr_emp_adjsalary');
    }
}