<?php

/**
 * PluginEmployeeAdjSalaryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEmployeeAdjSalaryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEmployeeAdjSalaryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEmployeeAdjSalary');
    }
}